title: XXL Steve
uglyURLs: false

defaultContentLanguage: en
languages:
  en:
    contentDir: content/en
    languageName: 🇺🇸
    weight: 1
  fr:
    contentDir: content/fr
    languageName: 🇫🇷
    weight: 2

author:
  name: XXL Steve

params:
  description: Welcome to my website
  images:
  - /favicon.png
  title: XXL Steve
  remark42SiteID: "xxlsteve.net"
  remark42Url: "https://xxlsteve.net/remark42"

social:
  twitter: cornetpanique86

taxonomies:
  tag: tags
  category: categories

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - rss
