title: XXL Steve
uglyURLs: false

defaultContentLanguage: en
languages:
  en:
    contentDir: content/en
    languageName: 🇺🇸
    weight: 1
  fr:
    contentDir: content/fr
    languageName: 🇫🇷
    weight: 2

author:
  name: XXL Steve

params:
  description: Welcome to my website
  title: XXL Steve
  remark42SiteID: "xxlsteve.net"
  remark42Url: "https://remark42.xxlsteve.net"

social:
  twitter: cornetpanique86

taxonomies:
  tag: tags
  category: categories

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - rss

enableRobotsTXT: true

security:
  gotemplates:
    allowActionJSTmpl: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: 'monokai'
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true