defaultContentLanguage: en
title: XXL Steve
uglyURLs: false

languages:
  en:
    contentDir: content/en
    languageName: 🇺🇸
    weight: 1
  fr:
    contentDir: content/fr
    languageName: 🇫🇷
    weight: 2

params:
  author: XXL Steve
  description: Welcome to my website
  images:
  - /favicon.png
  title: XXL Steve
  remark42SiteID: "xxlsteve.net"
  remark42Url: "http://comments.xxlsteve.net"

social:
  twitter: cornetpanique86

taxonomies:
  tag: tags
  category: categories

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputs:
  home:
    - html
    - json
  page:
    - html